# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-04 05:09
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('caption', models.CharField(blank=True, help_text='Image Caption. Optional', max_length=200)),
                ('summary', models.TextField()),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images')),
                ('caption', models.CharField(blank=True, help_text='Image Caption. Optional', max_length=200)),
                ('summary', models.TextField()),
                ('body', ckeditor.fields.RichTextField(verbose_name='Show Notes')),
                ('audio_embed', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
            },
        ),
    ]
